apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-package.fullname" . }}
  labels:
    {{- include "base-package.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.additional_service.enabled .Values.additional_service.port }}
    - port: {{ .Values.additional_service.port }}
      targetPort: http2
      protocol: TCP
      name: http2
    {{- end }}
  selector:
    {{- include "base-package.selectorLabels" . | nindent 4 }}
