name: Update Index

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Update Index
        run: |
          helm package .
          helm repo index .
          git config user.name "Helm Updater"
          git config user.email "actions@users.noreply.github.com"
          git add index.yaml
          git commit -m "Updated from ref: $GITHUB_SHA"
          git push
